# Generated by Django 5.2.5 on 2025-08-19 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerdetail',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='offers_app.offer'),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='revisions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='features',
            field=models.JSONField(default=list, help_text='List of feature strings'),
        ),
    ]
