# Generated by Django 5.2.5 on 2025-08-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0002_offerdetail_offer_offerdetail_revisions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='offerdetail',
            constraint=models.UniqueConstraint(fields=('offer', 'offer_type'), name='uniq_offer_offer_type'),
        ),
    ]
