# Generated by Django 5.2.5 on 2025-08-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0003_alter_offer_min_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=10),
        ),
    ]
